baseURL = "https://bigbanonos.com/"
title = "BigBanonos"
description = "BigBanonos: The best in Trap, Hip-Hop, and Chopped & Screwed playlists."
theme = "PaperMod"
enableRobotsTXT = true
ignoreErrors = ["error-remote-getjson", "error-missing-file"]

# THIS FIXES THE ERROR
[pagination]
  pagerSize = 21

[markup.goldmark.renderer]
  unsafe = true   # keeps your old embeds working

[taxonomies]
  tag = "tags"

[permalinks]
  posts = "/:slug/"

[params]
  ShowShareButtons = true
  disableThemeToggle = true
  defaultTheme = "light"

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

[[menu.main]]
  name = "Tags"
  url = "/tags/"
  weight = 2