baseURL = "https://bigbanonos.com/"
title = "BigBanonos"
description = "BigBanonos: The best in Trap, Hip-Hop, and Chopped & Screwed playlists."
theme = "PaperMod"
enableRobotsTXT = true

buildDrafts = true
buildFuture = true
buildExpired = true

ignoreErrors = ["error-remote-getjson", "error-missing-file", "alias-trailing-component"]

[outputs]
  home = ["HTML", "RSS", "JSON"]

[pagination]
  pagerSize = 21

[markup.goldmark.renderer]
  unsafe = true

[taxonomies]
  tag = "tags"

[permalinks]
  posts = "/:slug/"

[params]
  author = "BigBanonos"
  ShowShareButtons = true
  disableThemeToggle = true
  defaultTheme = "light"
  mainSections = ["posts"]
  ShowCodeCopyButtons = true
  defaultImageWidth = 500
  defaultImageHeight = 300

[params.fuseOpts]
  isCaseSensitive = false
  shouldSort = true
  location = 0
  distance = 1000
  threshold = 0.4
  minMatchCharLength = 0
  keys = ["title", "tags", "summary"]

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

[[menu.main]]
  name = "Tags"
  url = "/tags/"
  weight = 2

[[menu.main]]
  name = "Search"
  url = "/search/"
  weight = 3
