baseURL = "https://bigbanonos.com/"
title = "BigBanonos"
description = "BigBanonos: The best in Trap, Hip-Hop, and Chopped & Screwed playlists."
theme = "PaperMod"
enableRobotsTXT = true

# GOD MODE: FORCE EVERYTHING TO SHOW
buildDrafts = true
buildFuture = true
buildExpired = true

# IGNORE ERRORS
ignoreErrors = ["error-remote-getjson", "error-missing-file"]

# ALLOWS SEARCH TO WORK
[outputs]
  home = ["HTML", "RSS", "JSON"]

[pagination]
  pagerSize = 21

[markup.goldmark.renderer]
  unsafe = true   # keeps your old embeds working

[taxonomies]
  tag = "tags"

[permalinks]
  posts = "/:slug/"

[params]
  ShowShareButtons = true
  disableThemeToggle = true
  defaultTheme = "light"

# --- MENU BUTTONS ---
[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

[[menu.main]]
  name = "Tags"
  url = "/tags/"
  weight = 2

[[menu.main]]
  name = "Search"
  url = "/search/"
  weight = 3