baseURL = "https://bigbanonos.com/"
title = "BigBanonos"
description = "BigBanonos: The best in Trap, Hip-Hop, and Chopped & Screwed playlists."
theme = "PaperMod"
enableRobotsTXT = true

# GOD MODE: FORCE EVERYTHING TO SHOW
buildDrafts = true
buildFuture = true
buildExpired = true

# IGNORE ERRORS
ignoreErrors = ["error-remote-getjson", "error-missing-file"]

# ALLOWS SEARCH TO WORK (Generates index.json)
[outputs]
  home = ["HTML", "RSS", "JSON"]

[pagination]
  pagerSize = 21

[markup.goldmark.renderer]
  unsafe = true   # keeps your old embeds working

[taxonomies]
  tag = "tags"

[permalinks]
  posts = "/:slug/"

[params]
  ShowShareButtons = true
  disableThemeToggle = true
  defaultTheme = "light"
  
  # CRITICAL: Tells Homepage to list items from "posts" folder
  mainSections = ["posts"] 
  
  # CRITICAL: Makes tags look cleaner
  ShowCodeCopyButtons = true

# --- SEARCH ENGINE SETTINGS (You were missing this!) ---
[params.fuseOpts]
  isCaseSensitive = false
  shouldSort = true
  location = 0
  distance = 1000
  threshold = 0.4
  minMatchCharLength = 0
  keys = ["title", "tags", "content", "summary"]

# --- MENU BUTTONS ---
[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

[[menu.main]]
  name = "Tags"
  url = "/tags/"
  weight = 2

[[menu.main]]
  name = "Search"
  url = "/search/"
  weight = 3