baseURL = "https://bigbanonos.com/"
title = "BigBanonos"
theme = "PaperMod"
disableAliases = true
disablePathToLower = false
removePathAccents = true



ignoreFiles = ['^quarantine/']


[pagination]
  pagerSize = 6

enableRobotsTXT = true

[markup.goldmark.renderer]
  unsafe = true   # allow YouTube/Spotify iframes

[taxonomies]
  tag = "tags"

[permalinks]
 posts = "/:filename/"



[params]
  ShowShareButtons = true
  disableThemeToggle = true
  defaultTheme = "light"

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

[[menu.main]]
  name = "Tags"
  url = "/tags/"
  weight = 2
