baseURL = "https://bigbanonos.com/"
title = "BigBanonos"
theme = "PaperMod"
disableAliases = true
disablePathToLower = false
removePathAccents = true

ignoreFiles = ['^quarantine/']

[pagination]
  pagerSize = 6

enableRobotsTXT = true

[markup.goldmark.renderer]
  unsafe = true            # Allows your custom HTML/Shortcodes to run
  hardLineBreak = false

[taxonomies]
  tag = "tags"

[permalinks]
  posts = "/:contentbasename/"

[params]
  showFullContents = false    # CRITICAL: This stops 6 videos loading at once on Home
  ShowShareButtons = true
  disableThemeToggle = true
  defaultTheme = "light"

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

[[menu.main]]
  name = "Tags"
  url = "/tags/"
  weight = 2
